name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16
          cache: npm
      - name: Install npm dependencies
        run: npm install
      - name: Cache Composer dependencies
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install composer dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.3
          version: 2
          dev: yes
          quiet: yes
          args: --optimize-autoloader --classmap-authoritative --prefer-dist
      - name: Run Unit tests
        run: vendor/bin/phpunit tests
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release

